name: 'OI_Foundation'
version: '1.0.0'
config-version: 2

profile: 'default'

vars:
  primex_db: 'ETL_STAGING_UAT'
  primex_schema: 'SYSPRO_PRIMEX'
  primex_companies: ['A', 'C', 'P', 'X']
  primex_schemas: ['PRIMEX_SYSPRO_COMPANYA_DBO', 'PRIMEX_SYSPRO_COMPANYC_DBO', 'PRIMEX_SYSPRO_COMPANYP_DBO', 'PRIMEX_SYSPRO_COMPANYX_DBO']

  excluded_ax_companies: ('044', '045', '047', '999')
  fnd_tbl_db: 'OI_DATA_DEV_V2'
  fnd_tbl_sch: 'FND_DEV_BKP'
  intermediate_tbl_sch: 'INTERMEDIATE_FND_BKP'
  
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"
  
models:
  OI_Foundation:
    ax:
      +schema: intermediate_fnd_bkp
      materialized: incremental
      transient: false
      tmp_models:
        materialized: ephemeral
    ns:
      +schema: intermediate_fnd_bkp
      materialized: incremental
      transient: false
      tmp_models:
        materialized: ephemeral
    jde_hnck:
      +schema: intermediate_fnd_bkp
      materialized: incremental
      transient: false
      tmp_models:
        materialized: ephemeral
    syspro_prmx:
      +schema: intermediate_fnd_bkp
      materialized: incremental
      transient: false
      tmp_models:
        materialized: ephemeral
    foundation:
      materialized: table
      transient: false
    support_tables:
      +schema: intermediate_fnd_bkp
      materialized: table
      transient: false
    history:
      +schema: intermediate_fnd_bkp
      materialized: view