name: 'OI_Foundation'
version: '1.0.0'
config-version: 2

profile: 'default'

vars:
  db: 'OI_DATA_DEV_V2'
  schema: 'FND_DEV_TEST'
  primex_db: 'MULE_STAGING'
  primex_schema: 'SYSPRO_PRIMEX'
  primex_companies: ['A', 'C', 'P', 'X']

  excluded_ax_companies: ('044', '045', '047', '999')
  fnd_tbl_db: 'OI_DATA_DEV_V2'
  fnd_tbl_sch: 'FND_DEV_TEST'
  intermediate_tbl_sch: 'FND_DEV_TEST'
  
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"
  
models:
  OI_Foundation:
    ax:
      +schema: FND_DEV_TEST
      materialized: incremental
      transient: false
    ns:
      +schema: FND_DEV_TEST
      materialized: incremental
      transient: false
    jde:
      +schema: FND_DEV_TEST
      materialized: incremental
      transient: false
    primex:
      +schema: FND_DEV_TEST
      materialized: incremental
      transient: false
    foundation:
      +schema: FND_DEV_TEST
      materialized: table
      transient: false
    support_tables:
      +schema: FND_DEV_TEST
      materialized: table
      transient: false
    views:
      +schema: FND_DEV_TEST
      materialized: view