version: 2

sources:
  - name: AX_DEV
    database: FIVETRAN
    schema: AX_PRODREPLICATION1_DBO
    tables:
      - name: INVENTTABLE
      - name: CUSTTABLE
      - name: CUSTPRECASTCODE_OPI
      - name: COMPANYINFO
      - name: INVENTSITE
      - name: INVENTLOCATION
      - name: CUSTGROUP
      - name: CUSTPAYMMODETABLE
      - name: CUSTPRECASTCATEGORY_OPI
      - name: CURRENCY
      - name: PAYMTERM
      - name: CASHDISC
      - name: COMMISSIONCUSTOMERGROUP
      - name: ADDRESS
      - name: SALESTABLE
      - name: VENDTABLE
      - name: CONTACTPERSON
      - name: DIMENSIONS
      - name: UNIT
      - name: INVENTDIMGROUP
      - name: INVENTITEMBUYERGROUP
      - name: INVENTITEMGROUP
      - name: INVENTMODELGROUP
      - name: INVENTPRECASTCATEGORY_OPI
      - name: INVENTPRECASTCODE_OPI
      - name: INVENTPRODUCTCLASS_OPI
      - name: REQGROUP
      - name: INVENTSALESCLASS_OPI
      - name: INVENTSIZE
      - name: INVENTDIM
      - name: INVENTITEMPRICE
      - name: LEDGERTABLE
      - name: LEDGERBALANCESDIMTRANS
      - name: INVENTITEMLOCATION
      - name: INVENTSUM
      - name: INVENTTABLEMODULE
      - name: INVENTTRANS
      - name: DLVTERM
      - name: DLVMODE
      - name: SALESLINE
      - name: LEDGERTRANS
      - name: PURCHTABLE
      - name: PURCHLINE
      - name: PROJTABLE
      - name: VENDTRANS
      - name: VENDINVOICEJOUR
      - name: CUSTTRANS
      - name: CUSTSETTLEMENT
      - name: PRICEDISCGROUP
      - name: PROJCATEGORY
      - name: WMSPICKINGROUTE
      - name: PROJCOSTTRANS
      - name: CUSTTRANSOPEN
      - name: CUSTPACKINGSLIPJOUR
      - name: CUSTPACKINGSLIPTRANS
      - name: CUSTINVOICEJOUR
      - name: CUSTINVOICETRANS
      - name: VENDINVOICETRANS
      - name: VENDPACKINGSLIPJOUR
      - name: VENDPACKINGSLIPTRANS
      - name: PROJITEMTRANS
      - name: PROJEMPLTRANS
      - name: PROJFORECASTCOST 
      - name: PROJFORECASTEMPL
      - name: PROJTRANSPOSTING
      - name: PROJREVENUE_OPI

  - name: AX_PRODVIEW
    database: FIVETRAN
    schema: AX_PRODVIEW_DBO
    tables:
      - name: DIM_TIME_93

  - name: NS_DEV
    database: FIVETRAN
    schema: NETSUITE
    tables:
      - name: PAYMENT_TERMS
      - name: PAYMENT_METHODS
      - name: CURRENCIES
      - name: LOCATIONS
      - name: DEPARTMENTS
      - name: COMPANY_OPI
      - name: REGION_OPI
      - name: SUBREGION_OPI
      - name: ACCOUNTS
      - name: TRANSACTIONS
      - name: TRANSACTION_LINES
      - name: ACCOUNTING_PERIODS
      - name: MARKET_OPI
      - name: CLASSES
      - name: UOM
      - name: SUBSIDIARIES

  - name: JDE_HNCK_DEV1
    database: ETL_STAGING_UAT
    schema: HANCOCK_JDE_JDEPRODUCTION_PRODDTA
    tables:
      - name: F0013
      - name: F0901
      - name: F0006
      - name: F0902
      - name: F0911
      - name: F0010
      - name: F0101
      - name: F01151

  - name: JDE_HNCK_DEV2
    database: ETL_STAGING_UAT
    schema: HANCOCK_JDE_JDEPRODUCTION_PRODCTL
    tables:
      - name: F0005

  - name: JDE_HNCK_DEV3
    database: ETL_STAGING_UAT
    schema: HANCOCK_JDE_JDE920_DD920
    tables:
      - name: F9210

  - name: JDE_NPP_DEV1
    database: ETL_STAGING_UAT
    schema: NPP_JDE_JDEPRODUCTION_PRODDTA
    tables:
      - name: F0013
      - name: F0010
      - name: F0101
      - name: F0006
      - name: F0901
      - name: F0911
      - name: F0902

  - name: JDE_NPP_DEV2
    database: ETL_STAGING_UAT
    schema: NPP_JDE_JDEPRODUCTION_PRODCTL
    tables:      
      - name: F0005